In [ ]:
# Numpy

- numerical python

why?

- numpy is a python package used for computation and processing of a single dim and multi array
- it is very fast
- beacuse it is wriiten in c prograaming and embbedded in python
- numpy provides covienet and efficent way to handle large amount of data and chnaging the shape of an array 

- ARRAY ONLY CONTAINS THE HOMOGENOUS DATA

In [ ]:
school - matrix - 1,2,3,4,d
prograaming - array - 1,2,3,4
deep learning - tensor

In [2]:
# installing of libraires

!pip install numpy

SyntaxError: invalid syntax (<ipython-input-2-da13aaac669d>, line 3)

In [6]:
# impoirt the lib
import numpy as np

# Creation of an array

In [7]:
# 1. list

list1 = [1,2,3,4,5]
print(list1, type(list1))

# convetr to array
arr = np.array(list1)
print(arr , type(arr))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [8]:
# 2. tuple

tup1 = (1,2,3,4,5)
print(tup1, type(tup1))

# convetr to array
arr = np.array(tup1)
print(arr , type(arr))

(1, 2, 3, 4, 5) <class 'tuple'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [11]:
# few important attributes

# 1. size - how many elements ?
print(arr.size)

# 2. shape - what is the shape?
print(arr.shape)
"""
it will always return a tuple
the number of element in the tuples corrsponbd to the dim
"""

# 3. ndim - what is the dim of an array?
print(arr.ndim)

5
(5,)
1


In [ ]:
(5,)

In [ ]:
scalar - 45 - 0day array
vector - [1,2,3,4,5] - 1d array
2d - rows, columns
3d - row , columns, dept

In [12]:
list1 = [[1,2],[3,4],[5,6]]
print(list1, type(list1))

# convetr to array
arr = np.array(list1)
print(arr , type(arr))

[[1, 2], [3, 4], [5, 6]] <class 'list'>
[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>


In [15]:
# how many elements
print(arr.size)
# what is the shape
print(arr.shape)
# what is the dim
print(arr.ndim)

6
(3, 2)
2


In [ ]:
(3, 2) ---> (rows,column)
(3,2,4) --> (row, column , dept)

In [21]:
# 3. arange  --> will awlays give you 1d array( vector)

arr = np.arange(0,20,2)
print(arr, type(arr))

[ 0  2  4  6  8 10 12 14 16 18] <class 'numpy.ndarray'>


In [18]:
list(range(5,1,1))

[]

In [ ]:
arange

20 -start
2 - stop
step - 1

In [30]:
# 4. linspace

# arr = np.linspace(start , end , how many equal divisons)
arr = np.linspace(1 , 50 , 100 , dtype = None)
arr

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [32]:
# 5. zeros 

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [34]:
# 6. zero_like

np.zeros_like(arr)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
# 5. ones 

np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [36]:
# 6. ones_like

np.ones_like(arr)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
# 7. identiy matrix - 

"""
n*n

all dig are 1 and others are zero
"""

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
# 8. random values
# np.random.seed(101)
np.random.rand(2,6)

array([[0.86509982, 0.83027771, 0.53816145, 0.92246937, 0.09714648,
        0.10284749],
       [0.7015073 , 0.89047987, 0.1595603 , 0.27557254, 0.67249153,
        0.16430312]])

In [ ]:
np.random.rand

In [66]:
np.random.rand(2,6)

array([[0.28589569, 0.85239509, 0.97500649, 0.88485329, 0.35950784,
        0.59885895],
       [0.35479561, 0.34019022, 0.17808099, 0.23769421, 0.04486228,
        0.50543143]])

In [ ]:
# Changing the shape of an array - Reshaping

In [80]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [82]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [84]:
print(a.reshape(4,10))

"""
2d - 
2,10
4,5
10,2
5,4
1,20
20,1
"""

ValueError: cannot reshape array of size 20 into shape (4,10)

In [91]:
np.arange(15).reshape(5,3,1)

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14]]])

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [ ]:
# RULES FOR RESHAPING

matrix 1 - 50 - vector - 1d
matrix 2 - 2d - shape = 2,10

In [93]:
# infer

arr_1 = np.ones((786,786,64))



In [97]:
arr_1.reshape(-1,64).shape

(617796, 64)

In [ ]:
786*786*64 = x*64

In [96]:
786*786

617796

In [98]:
arr_1.reshape(786,-1).shape

(786, 50304)

In [103]:
# transpose of a matrix

# row,column = column , rows

a2 = np.arange(18).reshape(6,3)
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [101]:
a2.shape

(6, 3)

In [102]:
a2.T

array([[ 0,  3,  6,  9, 12, 15],
       [ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17]])

In [ ]:
# ravel() , flatten()

convet any dimesion matrix to 1 d

In [105]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [106]:
a2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
# basic operation on array

In [114]:
# arthmatic op on array - elementwise

a = np.array([10,20,30,4])
b = np.array([5,10,15,20])

In [115]:
a + b

array([15, 30, 45, 24])

In [116]:
a-b

array([  5,  10,  15, -16])

In [117]:
a*b

array([ 50, 200, 450,  80])

In [118]:
a/b

array([2. , 2. , 2. , 0.2])

In [119]:
a<30

array([ True,  True, False,  True])

In [ ]:
a = n*m
b = m*p

c -> n*p

In [121]:
a = np.array([[1,2,3] , [4,5,6]])
b = np.array([[1,2] , [3,4], [5,6]])

In [122]:
a.shape

(2, 3)

In [123]:
b.shape

(3, 2)

In [124]:
a.dot(b)

array([[22, 28],
       [49, 64]])

In [ ]:
# Unary operations

In [125]:
mat  = np.arange(0,20)

In [126]:
mat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [127]:
# what is the total sum of the element
mat.sum()

190

In [128]:
# what is the min of all the element
mat.min()

0

In [129]:
# what is the max of all the element
mat.max()

19

In [130]:
mat  = np.arange(0,20).reshape(5,4)

In [131]:
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [132]:
# what is the total sum of the element
mat.sum()

190

In [133]:
# what is the sum of all the columnms

"""
axis = 1 - rows
axis = 0 - columns
axis = None - all elemennts
"""
mat.sum(axis = 0)

array([40, 45, 50, 55])

In [134]:
# what is the sum of all the rows

"""
axis = 1 - rows
axis = 0 - columns
axis = None - all elemennts
"""
mat.sum(axis = 1)

array([ 6, 22, 38, 54, 70])

In [135]:
# what is the min of the element
mat.min()

0

In [136]:
# what is the min of all the columnms

"""
axis = 1 - rows
axis = 0 - columns
axis = None - all elemennts
"""
mat.min(axis = 0)

array([0, 1, 2, 3])

In [137]:
# what is the max of all the columnms

"""
axis = 1 - rows
axis = 0 - columns
axis = None - all elemennts
"""
mat.max(axis = 0)

array([16, 17, 18, 19])

In [138]:
# what is the min of all the rows

"""
axis = 1 - rows
axis = 0 - columns
axis = None - all elemennts
"""
mat.min(axis = 1)

array([ 0,  4,  8, 12, 16])

In [139]:
# what is the max of all the rows

"""
axis = 1 - rows
axis = 0 - columns
axis = None - all elemennts
"""
mat.max(axis = 1)

array([ 3,  7, 11, 15, 19])

In [140]:
# universal functions

a = np.array([10,20,30,4])
b = np.array([5,10,15,20])

In [141]:
np.add(a,b)

array([15, 30, 45, 24])

In [142]:
np.subtract(a,b)

array([  5,  10,  15, -16])

In [143]:
np.multiply(a,b)

array([ 50, 200, 450,  80])

In [145]:
a = np.array([[1,2,3] , [4,5,6]])
b = np.array([[1,2] , [3,4], [5,6]])
np.dot(a,b)

array([[22, 28],
       [49, 64]])

In [146]:
# trignomertry

a = np.array([10,20,30,4])
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162, -0.7568025 ])

In [147]:
a = np.array([10,20,30,4])
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.65364362])

In [148]:
# mean - 
np.mean(a)

16.0

In [149]:
# median
np.median(a)

15.0

In [150]:
np.std(a)

9.899494936611665

In [151]:
np.var(a)

98.0

In [ ]:
# Indexing and Slicing

In [152]:
a

array([10, 20, 30,  4])

In [153]:
a[-1]

4

In [154]:
a[-4]

10

In [155]:
# slicing
a[1::-1]

array([20, 10])

In [156]:
a[::-1]

array([ 4, 30, 20, 10])

In [157]:
# Two dim data

b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [160]:
b[1][-1]
b[1,1]
# [[0, 1, 2],[3, 4, 5]]

4

In [161]:
# slicing 
b

array([[0, 1, 2],
       [3, 4, 5]])

In [163]:
b[1,1:]

array([4, 5])

In [ ]:
b[row,column

In [164]:
a1 = np.arange(25).reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [165]:
a1[1,2:4]

array([7, 8])

In [166]:
a1[3:,3:]

array([[18, 19],
       [23, 24]])

In [167]:
a1[::2,2::2]

array([[ 2,  4],
       [12, 14],
       [22, 24]])

In [168]:
a1[1:4:2, :2] 

array([[ 5,  6],
       [15, 16]])

In [169]:
a1[1::2,:2] 

array([[ 5,  6],
       [15, 16]])

In [ ]:
5  6
15 16

# iterating over an array

In [170]:
a

array([10, 20, 30,  4])

In [171]:
for i in a:
    print(i)

10
20
30
4


In [172]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [173]:
for i in a1:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


In [ ]:
0
1
2
3
4
5
6
7
8

In [174]:
for i in a1:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [175]:
for i in a1.flatten():
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [ ]:
# website to practice
https://www.hackerrank.com
#
https://www.geeksforgeeks.org/python-numpy-practice-exercises-questions-and-solutions/